/**
 * Utility functions for TransGribator:
 * - Timecode formatting
 * - Subtitle export (SRT, VTT, TXT, JSON)
 * - File downloading
 */

export function formatDuration(seconds) {
  if (isNaN(seconds) || seconds === null || seconds === undefined) return '00:00';
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  if (hrs > 0) {
    return `${hrs.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

export function formatSrtTime(seconds) {
  if (isNaN(seconds) || seconds < 0) seconds = 0;
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);
  return `${hrs.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')},${millis.toString().padStart(3, '0')}`;
}

export function formatVttTime(seconds) {
  if (isNaN(seconds) || seconds < 0) seconds = 0;
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);
  return `${hrs.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}.${millis.toString().padStart(3, '0')}`;
}

export function generateSrt(segments) {
  return segments
    .filter((s) => s.text && s.text.trim())
    .map((seg, idx) => {
      const start = formatSrtTime(seg.start);
      const end = formatSrtTime(seg.end > seg.start ? seg.end : seg.start + 2);
      return `${idx + 1}\n${start} --> ${end}\n${seg.text.trim()}\n`;
    })
    .join('\n');
}

export function generateVtt(segments) {
  const body = segments
    .filter((s) => s.text && s.text.trim())
    .map((seg, idx) => {
      const start = formatVttTime(seg.start);
      const end = formatVttTime(seg.end > seg.start ? seg.end : seg.start + 2);
      return `${idx + 1}\n${start} --> ${end}\n${seg.text.trim()}\n`;
    })
    .join('\n');
  return `WEBVTT - Generated by TransGribator\n\n${body}`;
}

export function generateTxt(segments) {
  return segments
    .filter((s) => s.text && s.text.trim())
    .map((s) => s.text.trim())
    .join('\n\n');
}

export function generateJson(segments, metadata = {}) {
  const data = {
    app: 'TransGribator',
    exportedAt: new Date().toISOString(),
    metadata,
    segments: segments.map((s, index) => ({
      id: index + 1,
      start: parseFloat(s.start.toFixed(3)),
      end: parseFloat(s.end.toFixed(3)),
      startFormatted: formatDuration(s.start),
      endFormatted: formatDuration(s.end),
      text: s.text.trim(),
    })),
    fullText: segments.map((s) => s.text.trim()).join(' '),
  };
  return JSON.stringify(data, null, 2);
}

export function downloadFile(content, filename, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

export function formatBytes(bytes, decimals = 1) {
  if (!bytes || bytes === 0) return '0 B';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
}
